; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define <8 x i16> @vaddwev_h_b(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vaddwev_h_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.h.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %wa = sext <16 x i8> %pa to <16 x i16>
  %wb = sext <16 x i8> %pb to <16 x i16>
  %s = add <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vaddwev_h_bu(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vaddwev_h_bu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.h.bu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %wa = zext <16 x i8> %pa to <16 x i16>
  %wb = zext <16 x i8> %pb to <16 x i16>
  %s = add <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vaddwod_h_b(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vaddwod_h_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.h.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %wa = sext <16 x i8> %pa to <16 x i16>
  %wb = sext <16 x i8> %pb to <16 x i16>
  %s = add <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vaddwod_h_bu(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vaddwod_h_bu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.h.bu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %wa = zext <16 x i8> %pa to <16 x i16>
  %wb = zext <16 x i8> %pb to <16 x i16>
  %s = add <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vsubwev_h_b(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vsubwev_h_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.h.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %wa = sext <16 x i8> %pa to <16 x i16>
  %wb = sext <16 x i8> %pb to <16 x i16>
  %s = sub <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vsubwev_h_bu(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vsubwev_h_bu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.h.bu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %wa = zext <16 x i8> %pa to <16 x i16>
  %wb = zext <16 x i8> %pb to <16 x i16>
  %s = sub <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vsubwod_h_b(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vsubwod_h_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.h.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %wa = sext <16 x i8> %pa to <16 x i16>
  %wb = sext <16 x i8> %pb to <16 x i16>
  %s = sub <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <8 x i16> @vsubwod_h_bu(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: vsubwod_h_bu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.h.bu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <16 x i8> %a, <16 x i8> %a, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %pb = shufflevector <16 x i8> %b, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %wa = zext <16 x i8> %pa to <16 x i16>
  %wb = zext <16 x i8> %pb to <16 x i16>
  %s = sub <16 x i16> %wa, %wb
  %lo = shufflevector <16 x i16> %s, <16 x i16> %s, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %lo
}

define <4 x i32> @vaddwev_w_h(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vaddwev_w_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.w.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %wa = sext <8 x i16> %pa to <8 x i32>
  %wb = sext <8 x i16> %pb to <8 x i32>
  %s = add <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vaddwev_w_hu(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vaddwev_w_hu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.w.hu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %wa = zext <8 x i16> %pa to <8 x i32>
  %wb = zext <8 x i16> %pb to <8 x i32>
  %s = add <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vaddwod_w_h(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vaddwod_w_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.w.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %wa = sext <8 x i16> %pa to <8 x i32>
  %wb = sext <8 x i16> %pb to <8 x i32>
  %s = add <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vaddwod_w_hu(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vaddwod_w_hu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.w.hu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %wa = zext <8 x i16> %pa to <8 x i32>
  %wb = zext <8 x i16> %pb to <8 x i32>
  %s = add <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vsubwev_w_h(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vsubwev_w_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.w.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %wa = sext <8 x i16> %pa to <8 x i32>
  %wb = sext <8 x i16> %pb to <8 x i32>
  %s = sub <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vsubwev_w_hu(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vsubwev_w_hu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.w.hu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %wa = zext <8 x i16> %pa to <8 x i32>
  %wb = zext <8 x i16> %pb to <8 x i32>
  %s = sub <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vsubwod_w_h(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vsubwod_w_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.w.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %wa = sext <8 x i16> %pa to <8 x i32>
  %wb = sext <8 x i16> %pb to <8 x i32>
  %s = sub <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <4 x i32> @vsubwod_w_hu(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: vsubwod_w_hu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.w.hu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <8 x i16> %a, <8 x i16> %a, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %pb = shufflevector <8 x i16> %b, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %wa = zext <8 x i16> %pa to <8 x i32>
  %wb = zext <8 x i16> %pb to <8 x i32>
  %s = sub <8 x i32> %wa, %wb
  %lo = shufflevector <8 x i32> %s, <8 x i32> %s, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %lo
}

define <2 x i64> @vaddwev_d_w(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vaddwev_d_w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.d.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %wa = sext <4 x i32> %pa to <4 x i64>
  %wb = sext <4 x i32> %pb to <4 x i64>
  %s = add <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vaddwev_d_wu(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vaddwev_d_wu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwev.d.wu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %wa = zext <4 x i32> %pa to <4 x i64>
  %wb = zext <4 x i32> %pb to <4 x i64>
  %s = add <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vaddwod_d_w(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vaddwod_d_w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.d.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %wa = sext <4 x i32> %pa to <4 x i64>
  %wb = sext <4 x i32> %pb to <4 x i64>
  %s = add <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vaddwod_d_wu(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vaddwod_d_wu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddwod.d.wu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %wa = zext <4 x i32> %pa to <4 x i64>
  %wb = zext <4 x i32> %pb to <4 x i64>
  %s = add <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vsubwev_d_w(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vsubwev_d_w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.d.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %wa = sext <4 x i32> %pa to <4 x i64>
  %wb = sext <4 x i32> %pb to <4 x i64>
  %s = sub <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vsubwev_d_wu(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vsubwev_d_wu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwev.d.wu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %wa = zext <4 x i32> %pa to <4 x i64>
  %wb = zext <4 x i32> %pb to <4 x i64>
  %s = sub <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vsubwod_d_w(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vsubwod_d_w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.d.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %wa = sext <4 x i32> %pa to <4 x i64>
  %wb = sext <4 x i32> %pb to <4 x i64>
  %s = sub <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

define <2 x i64> @vsubwod_d_wu(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vsubwod_d_wu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsubwod.d.wu $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
  %pa = shufflevector <4 x i32> %a, <4 x i32> %a, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %pb = shufflevector <4 x i32> %b, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %wa = zext <4 x i32> %pa to <4 x i64>
  %wb = zext <4 x i32> %pb to <4 x i64>
  %s = sub <4 x i64> %wa, %wb
  %lo = shufflevector <4 x i64> %s, <4 x i64> %s, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %lo
}

